parser: babel-eslint
extends: airbnb

env:
  browser: true
  mocha: true

rules:
  camelcase: 0
  comma-dangle: 0
  no-bitwise: 0
  no-mixed-operators: 0
  semi: [2, always]
  prefer-promise-reject-errors: 0
  no-underscore-dangle: 0
  no-param-reassign: [error, { props: false }]
  no-plusplus: 0
  object-curly-spacing: [2, always]
  max-classes-per-file: 0
  arrow-parens: [2, as-needed, { requireForBlockBody: true }]
  react/sort-comp: 0
  react/no-danger: 0
  react/forbid-prop-types: 0
  react/static-property-placement: 0
  react/state-in-constructor: 0
  react/jsx-filename-extension: 0
  jsx-a11y/href-no-hash: 0
  jsx-a11y/anchor-is-valid: 0
  jsx-a11y/control-has-associated-label: 0
